# Generated by Django 5.1.15 on 2026-10-04 19:19

import django.core.validators
from decimal import Decimal
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('vencimento_atual', models.DateField(verbose_name='vencimento atual')),
                ('dia_vencimento', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='dia contratado')),
                ('emissao_pendente', models.BooleanField(default=False, help_text='Emissão iniciada: reconcilie com o Asaas antes de limpar este campo.')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('asaas_payment_id', models.CharField(blank=True, max_length=80)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('pix_expira_em', models.DateTimeField(blank=True, null=True)),
                ('lembrete_enviado_em', models.DateTimeField(blank=True, null=True)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'assinatura do sistema',
                'verbose_name_plural': 'assinatura do sistema',
            },
        ),
        migrations.CreateModel(
            name='EventoWebhookAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'evento webhook Asaas',
                'verbose_name_plural': 'eventos webhook Asaas',
                'ordering': ('-recebido_em',),
            },
        ),
    ]
