# Generated by Django 5.1.15 on 2026-10-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturasistema',
            name='nome_projeto',
            field=models.CharField(default='marmitaria_adriana', max_length=120, verbose_name='nome do projeto'),
        ),
        migrations.AddField(
            model_name='assinaturasistema',
            name='status_projeto',
            field=models.CharField(default='Em implementação', max_length=80, verbose_name='status'),
        ),
    ]
