# Generated by Django 4.2.6 on 2026-10-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobrancas', '0002_assinaturasistema_nome_projeto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinaturasistema',
            name='vencimento_pix',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
